version: "3.8"

services:
  productdb:
    image: mysql:8.0.30
  
  customerdb:
    image: postgres:alpine3.16

  portainer:
    image: portainer/portainer-ce

  pgadmin:
    image: dpage/pgadmin4

  product.api:
    image: ${DOCKER_REGISTRY-}product-api:${PLATFORM:-linux}-${TAG:-latest}
    build: 
      context: .
      dockerfile: Services/Product.API/Dockerfile

#network section
networks:
  default:
    name: aspnet
    driver: bridge

#volumes section
volumes:
  mysql_data:
    name: mysql_data

  portainer_data:
    name: portainer_data
  
  postgres_data:
    name: postgres_data

  pgadmin_data:
    name: pgadmin_data